import { Exercise } from './models';

export const exerciseLibrary: Exercise[] = [
  {
    id: 'pushup-standard',
    name: 'Push-Up',
    category: 'push-up',
    summary: 'Horizontal pressing pattern for chest, triceps, and trunk stiffness.',
    tags: {
      skill: [],
      strength: ['upper body push', 'core'],
      mobility: ['wrist', 'shoulder'],
      equipment: ['bodyweight'],
      level: 'beginner',
    },
    progression: {
      regression: 'Incline Push-Up',
      base: 'Push-Up',
      progression: 'Ring Push-Up',
    },
    contraindications: ['Acute wrist extension pain', 'Anterior shoulder irritation in deep ranges'],
    commonFaults: ['Sagging hips', 'Elbows flaring excessively', 'Neck craning forward'],
  },
  {
    id: 'ring-dip',
    name: 'Ring Dip',
    category: 'dip',
    summary: 'Vertical pressing variation with high shoulder stability demand.',
    tags: {
      skill: [],
      strength: ['upper body push', 'core'],
      mobility: ['shoulder', 'thoracic spine'],
      equipment: ['rings'],
      level: 'intermediate',
    },
    progression: {
      regression: 'Bench Dip (limited range)',
      base: 'Ring Dip',
      progression: 'Weighted Ring Dip',
    },
    contraindications: ['History of AC joint pain', 'Uncontrolled anterior humeral glide'],
    commonFaults: ['Internal shoulder collapse', 'Loss of ring turnout', 'Partial lockout with shrugged shoulders'],
  },
  {
    id: 'chin-up-strict',
    name: 'Strict Chin-Up',
    category: 'pull-up/chin-up',
    summary: 'Supinated vertical pull emphasizing biceps and lats.',
    tags: {
      skill: [],
      strength: ['upper body pull'],
      mobility: ['shoulder', 'thoracic spine'],
      equipment: ['pull-up bar'],
      level: 'beginner',
    },
    progression: {
      regression: 'Band-Assisted Chin-Up',
      base: 'Strict Chin-Up',
      progression: 'Weighted Chin-Up',
    },
    contraindications: ['Medial elbow tendinopathy flare-up', 'Acute shoulder impingement symptoms'],
    commonFaults: ['Kipping without intent', 'Forward head jut at top', 'Incomplete scapular depression'],
  },
  {
    id: 'ring-row',
    name: 'Ring Row',
    category: 'row',
    summary: 'Horizontal pull for scapular control and upper back strength.',
    tags: {
      skill: [],
      strength: ['upper body pull', 'core'],
      mobility: ['shoulder'],
      equipment: ['rings'],
      level: 'beginner',
    },
    progression: {
      regression: 'High-Angle Ring Row',
      base: 'Ring Row',
      progression: 'Feet-Elevated Ring Row',
    },
    contraindications: ['Acute biceps tendon irritation'],
    commonFaults: ['Shoulders drifting toward ears', 'Hips dropping out of plank', 'Shortened final elbow drive'],
  },
  {
    id: 'split-squat',
    name: 'Rear-Foot Elevated Split Squat',
    category: 'squat/lunge',
    summary: 'Single-leg squat/lunge hybrid to build leg strength and control.',
    tags: {
      skill: [],
      strength: ['lower body', 'core'],
      mobility: ['hip', 'ankle'],
      equipment: ['bench', 'bodyweight'],
      level: 'intermediate',
    },
    progression: {
      regression: 'Split Squat',
      base: 'Rear-Foot Elevated Split Squat',
      progression: 'Front-Rack Bulgarian Split Squat',
    },
    contraindications: ['Patellar tendon pain under deep knee flexion'],
    commonFaults: ['Front heel lifting', 'Knee collapsing inward', 'Overextension through lumbar spine'],
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    category: 'hinge',
    summary: 'Hip hinge for posterior chain strength and hamstring capacity.',
    tags: {
      skill: [],
      strength: ['lower body'],
      mobility: ['hamstring', 'hip'],
      equipment: ['barbell'],
      level: 'beginner',
    },
    progression: {
      regression: 'Dowel Hip Hinge',
      base: 'Romanian Deadlift',
      progression: 'Single-Leg Romanian Deadlift',
    },
    contraindications: ['Acute lumbar disc irritation', 'Unable to brace neutral trunk'],
    commonFaults: ['Bar drifting from body', 'Knees locking out hard', 'Losing spinal neutrality near bottom'],
  },
  {
    id: 'dead-bug-banded',
    name: 'Banded Dead Bug',
    category: 'core anti-extension/rotation',
    summary: 'Anti-extension and anti-rotation trunk patterning drill.',
    tags: {
      skill: [],
      strength: ['core'],
      mobility: ['thoracic spine', 'hip'],
      equipment: ['bodyweight'],
      level: 'beginner',
    },
    progression: {
      regression: 'Bodyweight Dead Bug',
      base: 'Banded Dead Bug',
      progression: 'Hollow Body Rock + Band Pull',
    },
    contraindications: ['Acute lumbar extension sensitivity'],
    commonFaults: ['Ribs flaring upward', 'Neck strain from head lift', 'Fast, uncontrolled limb motion'],
  },
  {
    id: 'handstand-wall',
    name: 'Wall Handstand Hold',
    category: 'skill',
    summary: 'Inversion skill for overhead line control and balance confidence.',
    tags: {
      skill: ['handstand'],
      strength: ['upper body push', 'core'],
      mobility: ['wrist', 'shoulder', 'thoracic spine'],
      equipment: ['bodyweight'],
      level: 'intermediate',
    },
    progression: {
      regression: 'Pike Hold on Box',
      base: 'Wall Handstand Hold',
      progression: 'Freestanding Handstand',
    },
    contraindications: ['Unmanaged blood pressure concerns with inversion', 'Acute wrist pain'],
    commonFaults: ['Banana back line', 'Shoulders not fully elevated', 'Hands placed too close to wall'],
  },
  {
    id: 'front-lever-tuck',
    name: 'Tuck Front Lever Hold',
    category: 'skill',
    summary: 'Straight-arm pulling skill for lat and trunk tension.',
    tags: {
      skill: ['front lever'],
      strength: ['upper body pull', 'core'],
      mobility: ['shoulder'],
      equipment: ['pull-up bar'],
      level: 'advanced',
    },
    progression: {
      regression: 'Tucked Inverted Hang',
      base: 'Tuck Front Lever Hold',
      progression: 'Advanced Tuck Front Lever',
    },
    contraindications: ['Distal biceps tendon pain', 'Shoulder pain in long-lever straight-arm loading'],
    commonFaults: ['Hip pike collapse', 'Elbow bend compensation', 'Scapular elevation under fatigue'],
  },
  {
    id: 'back-lever-tuck',
    name: 'Tuck Back Lever Hold',
    category: 'skill',
    summary: 'Straight-arm posterior chain and shoulder extension skill.',
    tags: {
      skill: ['back lever'],
      strength: ['upper body pull', 'core'],
      mobility: ['shoulder'],
      equipment: ['rings'],
      level: 'advanced',
    },
    progression: {
      regression: 'Skin-the-Cat Eccentric',
      base: 'Tuck Back Lever Hold',
      progression: 'Straddle Back Lever Hold',
    },
    contraindications: ['Anterior shoulder instability history'],
    commonFaults: ['Excessive lumbar arch', 'Bent elbows', 'Neck hyperextension to find horizon'],
  },
  {
    id: 'planche-lean',
    name: 'Planche Lean',
    category: 'skill',
    summary: 'Straight-arm pushing skill to build anterior chain compression.',
    tags: {
      skill: ['planche'],
      strength: ['upper body push', 'core'],
      mobility: ['wrist', 'shoulder'],
      equipment: ['parallettes'],
      level: 'advanced',
    },
    progression: {
      regression: 'Quadruped Lean',
      base: 'Planche Lean',
      progression: 'Tuck Planche Hold',
    },
    contraindications: ['Current wrist tendinopathy', 'Pain with protracted loading'],
    commonFaults: ['Elbows bending', 'Scapulae retracting', 'Hips piked instead of neutral'],
  },
  {
    id: 'muscle-up-transition',
    name: 'False-Grip Muscle-Up Transition',
    category: 'skill',
    summary: 'Transition drill linking pull and dip for ring muscle-up.',
    tags: {
      skill: ['muscle-up'],
      strength: ['upper body pull', 'upper body push', 'core'],
      mobility: ['wrist', 'shoulder'],
      equipment: ['rings'],
      level: 'advanced',
    },
    progression: {
      regression: 'Band-Assisted Transition Drill',
      base: 'False-Grip Muscle-Up Transition',
      progression: 'Strict Ring Muscle-Up',
    },
    contraindications: ['False grip aggravates wrist flexor pain'],
    commonFaults: ['Late turnover with chicken wing', 'Losing false grip', 'Rings drifting wide in dip'],
  },
  {
    id: 'l-sit-hold',
    name: 'L-Sit Hold',
    category: 'skill',
    summary: 'Compression-based isometric for hip flexors, trunk, and shoulder depression.',
    tags: {
      skill: ['L-sit'],
      strength: ['core', 'upper body push'],
      mobility: ['hamstring', 'hip', 'shoulder'],
      equipment: ['parallettes'],
      level: 'intermediate',
    },
    progression: {
      regression: 'Tuck Support Hold',
      base: 'L-Sit Hold',
      progression: 'V-Sit Pulses',
    },
    contraindications: ['Acute hip flexor strain', 'Wrist pain in loaded extension'],
    commonFaults: ['Rounded lumbar slump', 'Depressed shoulder position lost', 'Bent knees from poor compression'],
  },
];

export const movementCategories = [
  'push-up',
  'dip',
  'pull-up/chin-up',
  'row',
  'squat/lunge',
  'hinge',
  'core anti-extension/rotation',
  'skill',
] as const;

export const skillTags = ['handstand', 'front lever', 'back lever', 'planche', 'muscle-up', 'L-sit'] as const;
